In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("/home/user/Downloads/credit_risk_homeloans.csv")

In [4]:
data.shape

(5000, 13)

In [5]:
data.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,LP100000,14529,10654,562,180,1,Male,No,0,Graduate,No,Urban,Y
1,LP100001,22885,12859,496,84,0,Male,No,3+,Not Graduate,No,Rural,Y
2,LP100002,4156,10846,310,120,1,Male,Yes,3+,Graduate,Yes,Semiurban,Y
3,LP100003,4285,9311,419,120,1,Male,No,1,Not Graduate,No,Semiurban,Y
4,LP100004,18187,11156,52,360,0,Male,Yes,2,Graduate,No,Rural,N

In [7]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            5000 non-null   object
 1   ApplicantIncome    5000 non-null   int64
 2   CoapplicantIncome  5000 non-null   int64
 3   LoanAmount         5000 non-null   int64
 4   Loan_Amount_Term   5000 non-null   int64
 5   Credit_History     5000 non-null   int64
 6   Gender             5000 non-null   object
 7   Married            5000 non-null   object
 8   Dependents         5000 non-null   object
 9   Education          5000 non-null   object
 10  Self_Employed      5000 non-null   object
 11  Property_Area      5000 non-null   object
 12  Loan_Status        5000 non-null   object
dtypes: int64(5), object(8)
memory usage: 507.9+ KB
None

In [8]:
data.isnull().sum()

Loan_ID              0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
Property_Area        0
Loan_Status          0
dtype: int64

In [34]:
# Remove Loan_ID column
df = data.drop("Loan_ID", axis=1,inplace=True)

In [35]:
data.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,14529,10654,562,180,1,1,0,0,0,0,2,1
1,22885,12859,496,84,0,1,0,3,1,0,0,1
2,4156,10846,310,120,1,1,1,3,0,1,1,1
3,4285,9311,419,120,1,1,0,1,1,0,1,1
4,18187,11156,52,360,0,1,1,2,0,0,0,0

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
# Creating LabelEncoder object
le = LabelEncoder()

In [38]:
# Converting all categorical columns into numeric values
categorical_columns = [
    "Gender",
    "Married",
    "Dependents",
    "Education",
    "Self_Employed",
    "Property_Area",
    "Loan_Status"
]

In [39]:
for col in categorical_columns:
    data[col] = le.fit_transform(data[col])

In [40]:
data.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,14529,10654,562,180,1,1,0,0,0,0,2,1
1,22885,12859,496,84,0,1,0,3,1,0,0,1
2,4156,10846,310,120,1,1,1,3,0,1,1,1
3,4285,9311,419,120,1,1,0,1,1,0,1,1
4,18187,11156,52,360,0,1,1,2,0,0,0,0

In [41]:
# Features (Input)
x = data.drop("Loan_Status", axis=1)

In [42]:
# Target (Output)
y = data["Loan_Status"]

In [43]:
x.shape

(5000, 11)

In [44]:
y.shape

(5000,)

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)

In [47]:
# Checking the sizes
print("Training data:", x_train.shape)
print("Testing data:", x_test.shape)

Training data: (4000, 11)
Testing data: (1000, 11)

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(x_train, y_train)

train_pred = rf_model.predict(x_train)
test_pred = rf_model.predict(x_test)

print("Training Accuracy:", accuracy_score(y_train, train_pred))
print("Testing Accuracy:", accuracy_score(y_test, test_pred))

Training Accuracy: 1.0
Testing Accuracy: 0.687

In [60]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42
)

rf_model.fit(x_train, y_train)

train_pred = rf_model.predict(x_train)
test_pred = rf_model.predict(x_test)

print("Training Accuracy:", accuracy_score(y_train, train_pred))
print("Testing Accuracy:", accuracy_score(y_test, test_pred))

Training Accuracy: 0.73325
Testing Accuracy: 0.702

In [62]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Create model
rf = RandomForestClassifier(random_state=42)

# Grid Search
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

# Train
grid_search.fit(x_train, y_train)

# Best parameters
print("Best Parameters:", grid_search.best_params_)
print("Best Cross Validation Accuracy:", grid_search.best_score_)

Best Parameters: {'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}
Best Cross Validation Accuracy: 0.7057499999999999

In [64]:
from sklearn.metrics import accuracy_score

best_rf = grid_search.best_estimator_

# Predictions
train_pred = best_rf.predict(x_train)
test_pred = best_rf.predict(x_test)

# Accuracy
print("Training Accuracy:", accuracy_score(y_train, train_pred))
print("Testing Accuracy:", accuracy_score(y_test, test_pred))

Training Accuracy: 0.70875
Testing Accuracy: 0.706

In [65]:
best_rf = grid_search.best_estimator_

In [67]:
import joblib

joblib.dump(best_rf, "/home/user/Downloads/loan_prediction_model.pkl")

print("Model saved successfully!")

Model saved successfully!